
using QuestPDF.Fluent;

namespace Store.Core.Services
{
  public class ReportPdfGenerator
  {
    public static byte[] GenerateDailyReport(DateTime date, int? ordersCount, decimal? totalRevenue, int? newUsersCount)
    {
      return Document.Create(container =>
      {
        container.Page(page =>
        {
          page.Margin(30);

          // Header
          page.Header()
              .Text($"📅 Daily Report - {date:yyyy-MM-dd}")
              .FontSize(20).Bold().AlignCenter();

          // Content
          page.Content().PaddingVertical(10).Column(col =>
          {
            col.Item().Text($"📦 Orders Today: {ordersCount?.ToString() ?? "N/A"}").FontSize(14);
            col.Item().Text($"💰 Total Revenue: {(totalRevenue.HasValue ? totalRevenue.Value.ToString("C") : "N/A")}").FontSize(14);
            col.Item().Text($"👥 New Users: {newUsersCount?.ToString() ?? "N/A"}").FontSize(14);
          });

          // Footer
          page.Footer()
              .AlignCenter()
              .Text("Generated by Store System - " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm"));
        });
      }).GeneratePdf();
    }

    public static byte[] GenerateMonthlyReport(DateTime month, int? ordersCount, decimal? totalRevenue, int? newUsersCount)
    {
      return Document.Create(container =>
      {
        container.Page(page =>
        {
          page.Margin(30);

          // Header
          page.Header()
              .Text($"📅 Monthly Report - {month:MMMM yyyy}")
              .FontSize(20).Bold().AlignCenter();

          // Content
          page.Content().PaddingVertical(10).Column(col =>
          {
            col.Item().Text($"📦 Orders This Month: {ordersCount?.ToString() ?? "N/A"}").FontSize(14);
            col.Item().Text($"💰 Total Revenue: {(totalRevenue.HasValue ? totalRevenue.Value.ToString("C") : "N/A")}").FontSize(14);
            col.Item().Text($"👥 New Users: {newUsersCount?.ToString() ?? "N/A"}").FontSize(14);
          });

          // Footer
          page.Footer()
              .AlignCenter()
              .Text("Generated by Store System - " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm"));
        });
      }).GeneratePdf();
    }
  }
}